/* ─── Devicon CSS class map ───────────────────────────────────── */
export const DEVICON_MAP = {
  JavaScript: "devicon-javascript-plain colored",
  TypeScript: "devicon-typescript-plain colored",
  Python: "devicon-python-plain colored",
  "C++": "devicon-cplusplus-plain colored",
  HTML: "devicon-html5-plain colored",
  CSS: "devicon-css3-plain colored",
  SQL: "devicon-mysql-plain colored",
  MongoDB: "devicon-mongodb-plain colored",
  Postgres: "devicon-postgresql-plain colored",
  ReactJS: "devicon-react-original colored",
  "Next.js": "devicon-nextjs-plain",
  "Node.js": "devicon-nodejs-plain colored",
  SCSS: "devicon-sass-plain colored",
  Sass: "devicon-sass-plain colored",
  Redux: "devicon-redux-original colored",
  GSAP: "devicon-gsap-plain colored",
  "React Router": "devicon-reactrouter-plain colored",
  "Express.js": "devicon-express-original",
  "Tailwind CSS": "devicon-tailwindcss-plain colored",
  "Material UI": "devicon-materialui-plain colored",
  "Ant Design": "devicon-antdesign-plain colored",
  Git: "devicon-git-plain colored",
  "GitHub/GitLab": "devicon-github-original",
  "GitHub Actions": "devicon-githubactions-plain colored",
  Docker: "devicon-docker-plain colored",
  Kubernetes: "devicon-kubernetes-plain colored",
  AWS: "devicon-amazonwebservices-plain colored",
  Vite: "devicon-vitejs-plain colored",
  Jest: "devicon-jest-plain colored",
  Figma: "devicon-figma-plain colored",
  Postman: "devicon-postman-plain colored",
  "Webpack 5": "devicon-webpack-plain colored",
  Storybook: "devicon-storybook-plain colored",
  "AWS Cloudfront CDN": "devicon-amazonwebservices-plain colored",
};
