import {
  IIITA,
  Infoedge,
  Yugen,
  Breakout,
  NamasteDev,
  ArticleSummarizer,
  Canso,
  Ecommerce,
  Football,
  ImageGenerator,
  MinipageBuilder,
  MusicPlayer,
  NikeLanding,
  JavascriptCertificate,
  ReactCertificate,
} from "../assets/index";

const projects = [
  // {
  //   title: "Admin Dashboard (Breakout)",
  //   period: "Dec 2024 - Present",
  //   description:
  //     "End‑to‑end dashboard for operations and analytics. Implemented modular UI, role‑based views, and real‑time insights.",
  //   tags: [
  //     "React",
  //     "TypeScript",
  //     "Tailwind",
  //     "Framer Motion",
  //     "React Router",
  //     "React Hooks",
  //     "React Query",
  //     "React Context",
  //     "React Redux",
  //     "React Redux Toolkit",
  //     "AWS",
  //     "Cloudfront CDN",
  //     "Docker",
  //     "Kubernetes",
  //     "ArgoCD",
  //     "GIT",
  //     "GitHub/GitLab",
  //     "Technical Documentation",
  //     "Debugging",
  //     "Testing",
  //     "Software Design & Code Development",
  //   ],
  //   link: "https://dashboard.getbreakout.ai/",
  // },
  // {
  //   title: "AI Agentic ChatBot (Breakout)",
  //   period: "Dec 2024 - Present",
  //   description:
  //     "AI Agentic ChatBot for operations and analytics. Implemented modular UI, role‑based views, and real‑time insights.",
  //   tags: [
  //     "React",
  //     "TypeScript",
  //     "Tailwind",
  //     "Framer Motion",
  //     "React Router",
  //     "React Hooks",
  //     "React Query",
  //     "React Context",
  //     "React Redux",
  //     "React Redux Toolkit",
  //     "AWS",
  //     "Cloudfront CDN",
  //     "Docker",
  //     "Kubernetes",
  //     "ArgoCD",
  //     "GIT",
  //     "GitHub/GitLab",
  //     "Technical Documentation",
  //     "Debugging",
  //     "Testing",
  //     "Software Design & Code Development",
  //   ],
  //   link: "https://agent.getbreakout.ai/demo/org/hackerearth/agent/1/?bc=true",
  // },
  {
    photo: Canso,
    title: "Canso.ai",
    period: "Feb 2024",
    description:
      "This App provides Reimagine Fraud Control with AI Agents and MLOps",
    tags: [
      "React.js",
      "JavaScript",
      "Data Structures",
      "RESTful WebServices",
      "(CSS)",
      "Cross-browser Compatibility",
      "REST APIs",
      "Express.js",
      "AI Agents",
      "MLOps",
      "Docker",
      "Kubernetes",
      "ArgoCD",
      "GitHub Actions",
      "SEO optimization",
      "Data Visualisation UI",
      "OpenApi Specification Using Swagger",
      "Agile Methodologies",
      "UI/UX designs",
      "Figma",
      "Coding",
      "Debugging",
      "Production Support",
      "Technical Support",
    ],
    link: "https://drive.google.com/file/d/1O2Rk_hwXLyqAIgAZjsYWwXt0xb4ZHLEs/view?usp=sharing",
  },
  {
    photo: Football,
    title: "Football Manager App",
    period: "Dec 2023",
    description:
      "Footbal Manager App is an app which helps in managing footbal players efficiently via the interface, displaying all the details in a tabular format as well as showcasing the formation overview on the field for different type of players.",
    tags: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "Redux",
      "Clean Coding",
      "Data Structures",
      "Algorithms",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
    ],
    link: "https://football-manager-app-mu.vercel.app/",
  },
  {
    photo: Ecommerce,
    title: "E-Commerce App",
    period: "Nov 2023",
    description:
      "An E-commerce App showcasing features including Authentication, Cart, Orders, Stripe Payment Checkout Integration etc. powered by NextJS and visually appealing UI with error handling UIs powered by tailwindcss.",
    tags: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "NextJS",
      "Stripe",
      "Authentication",
      "Cart",
      "Orders",
      "Error Handling",
      "UI/UX Design",
      "Clean Coding",
      "Data Structures",
      "Algorithms",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
    ],
    link: "https://e-commerce-neon-nu.vercel.app/",
  },
  {
    photo: MinipageBuilder,
    title: "Mini-Page Builder App",
    period: "Oct 2023",
    description:
      "A page builder app where user can design a page based on given blocks like, Label, Input, Button which can be used as Drag and Drop. User can also export the JSOn representation of the configuration of the page.",
    tags: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "React Hooks",
      "Data Structures",
      "Algorithms",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
    ],
    link: "https://mini-page-builder-orcin.vercel.app/",
  },
  {
    photo: ImageGenerator,
    title: "Image Generator",
    period: "Sep 2023",
    description:
      "This App provides user to create an image using prompts powered by openAI image generation API , visually striken and showcasing them in a commnity page , implying all users can see the AI Image.",
    tags: [
      "React.js",
      "Attention to Detail",
      "Clean Coding",
      "Cloudinary",
      "JavaScript",
      "Data Structures",
      "RESTful WebServices",
      "Node.js",
      "Algorithms",
      "openAI",
      "Cascading Style Sheets (CSS)",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
      "REST APIs",
      "Express.js",
    ],
    link: "https://envision-image.netlify.app/",
  },
  {
    photo: MusicPlayer,
    title: "Music Player App",
    period: "Sep 2023",
    description:
      "This app showcase music player features playing songs, top charts and artists, using React fundamentals to develop the core features and functionality of app and Visually striken user-centeric UI powered by tailwindcss.",
    tags: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "React Hooks",
      "Data Structures",
      "Algorithms",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
    ],
    link: "https://nirvana-musik-app.netlify.app/",
  },
  {
    photo: ArticleSummarizer,
    title: "Article Summarizer App",
    period: "Aug 2023",
    description:
      "Article Summarizer app helps in providing summary about any article. User can just provide the link with the article, and then User can get Brief Summary of the article.",
    tags: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "React Hooks",
      "Data Structures",
      "Algorithms",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
      "REST APIs",
    ],
    link: "https://openai-article-summary.netlify.app/",
  },
  {
    photo: NikeLanding,
    title: "Nike Landing App",
    period: "Aug 2023",
    description:
      "This App showcase a user centric & attractive UI , using the powerful concepts of TailwindCSS and Reactjs, It was a step forward to learning the fundamentals of tailwindcss.",
    tags: [
      "React.js",
      "Attention to Detail",
      "Clean Coding",
      "JavaScript",
      "Data Structures",
      "Tailwind CSS",
      "Algorithms",
      "Cascading Style Sheets (CSS)",
      "Problem Solving",
      "Skill Development",
      "Cross-browser Compatibility",
    ],
    link: "https://nike-landing-ui-app.netlify.app/",
  },
];

const certificates = [
  {
    photo: JavascriptCertificate,
    title: "Namaste JavaScript",
    issuer: NamasteDev,
    credentialId: "6UEH16",
    link: "https://drive.google.com/uc?export=view&id=1y-hMXEDmlipiMlFUxtWPrtwR--BUAvVP",
  },
  {
    photo: ReactCertificate,
    title: "Namaste React",
    issuer: NamasteDev,
    credentialId: "3HGTHN",
    link: "https://drive.google.com/uc?export=view&id=1-CjhIF6s1zJQUMfGPc0WjgXUrXW-uN9_",
  },
];

const extensiveSkills = [
  "ReactJS",
  "Javascript",
  "Typescript",
  "Redux",
  "Python",
  "Webpack",
  "Tanstack libraries",
  "Websocket",
  "Storybook",
  "Monorepo Structure",
  "RTL",
  "GSAP",
  "REST API Integration",
  "JWT",
  "SOLID",
  "Node.js",
  "OWASP Compliance",
  "ZAP pen-testing",
  "Postgres",
  "Ant Design",
  "Webpack 5",
  "Tailwind CSS",
  "SCSS",
  "MongoDB",
  "Azure",
  "AWS",
  "CI/CD",
  "LLMs",
  "Cloudfront CDN",
  "Docker",
  "Kubernetes",
  "ArgoCD",
  "GitHub Actions",
  "PWA",
  "C++",
  "Java",
  "SEO optimization",
  "Data Visualisation UI",
  "OpenApi Specification Using Swagger",
  "Agile Methodologies",
  "UI/UX designs",
  "Figma",
  "Coding",
  "Debugging",
  "Production Support",
  "Technical Support",
];

const conceptTags = [
  "Functional Component",
  "Node",
  "React Router",
  "Asynchronous Programming",
  "Routing",
  "Optimizing React Apps",
  "Modules",
  "Code Splitting",
  "Building Live Projects",
  "Pure Components",
  "Service Worker",
  "Asynchronous Hooks",
  "Rest API",
  "Error Handling",
  "Color Contrasts",
  "Concurrency",
  "SSJI",
  "Building Live Projects",
  "Telemetry",
  "HTTPS",
  "Tailwind CSS",
  "Handling Events",
  "Authentication",
  "Pure Components",
  "Functional Comp.",
  "Code Splitting",
  "Rich and Interactive UI",
  "Scaling React Apps",
  "Optimizing React Apps",
  "Interview Questions",
  "Networking",
  "Rich and Interactive UI",
  "Polyfills",
  "Bundlers & Babel",
  "React Hooks",
  "React.Fragment",
  "State Management",
  "Routing",
  "Modules",
  "Concurrency",
  "React Testing Library",
  "Microfrontend",
  "Server Sent Event",
  "Reusable Components",
  "libuv",
  "Building Live Projects",
  "Non-blocking I/O",
  "Pure Components",
  "IFrame Protection",
];

const timeline = [
  {
    period: "2015-2017",
    link: "https://britishenglishschool.in/",
    headTitle: "British English School",
    title: "Completed CBSE‑12",
    subtitle: "84.2%",
    points: [
      "Strong foundation in math and science; early interest in software.",
    ],
  },
  {
    icon: IIITA,
    period: "Jul 2017 - May 2021",
    link: "https://www.iiita.ac.in/",
    headTitle: "Indian Institute Of Information Technology Allahabad",
    title: "Bachelor of Technology - BTech, Information Technology",
    subtitle: "CGPA: 6.83",
    points: [
      "Honed strong interpersonal skills through collaboration and teamwork.",
      "Successfully built multiple projects for semester courses, demonstrating creativity and technical expertise.",
      "Applied knowledge of software engineering concepts to real-world scenarios, enhancing my learning and problem-solving abilities.",
      "Actively participated in hackathons, sports, and various events, further building leadership and teamwork skills while maintaining a balanced approach to academic and extracurricular activities.",
    ],
    skills: [
      "JavaScript",
      "Computer Science",
      "Algorithms",
      "Python (Programming Language)",
      "Communication",
      "React Hooks",
      "Microsoft Office",
      "Clean Coding",
      "Web Development",
      "C (Programming Language)",
      "SQL",
      "Web Applications",
      "Problem Solving",
      "Attention to Detail",
      "Cascading Style Sheets (CSS)",
      "HTML",
      "redux",
      "React.js",
      "Data Structures",
      "Computer Architecture",
      "Operating Systems",
      "Artificial Intelligence (AI)",
      "Object-Oriented Programming (OOP)",
    ],
  },
  {
    icon: Infoedge,
    period: "Sep 2021 - Jul 2023",
    link: "https://www.naukri.com/",
    headTitle: "Infoedge (Naukri.com)",
    title: "Software Engineer",
    points: [
      "Managed and enhanced recruiter‑side UI, optimizing Job Posting form and Response Manager components.",
      "Implemented search filters improving candidate search efficiency by ~40%.",
      "Owned features across the SDLC: design, development, testing, debugging, and post‑production support.",
    ],
    skills: [
      "React",
      "TypeScript",
      "Sass",
      "Redux",
      "Material UI",
      "RTL",
      "Jest",
    ],
  },
  {
    icon: Yugen,
    period: "Feb 2024 - Oct 2024",
    link: "https://www.yugen.ai/",
    headTitle: "Yugen.ai",
    title: "Frontend Engineer",
    points: [
      "Collaborated with Platform Engineering to build a web application from scratch to streamline user access.",
      "Led API integration, architecture and system design; leveraged AWS, Docker, and Kubernetes.",
    ],
    skills: [
      "React",
      "Micro‑frontends",
      "JavaScript",
      "API Integration",
      "Webpack 5",
      "AWS",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    icon: Breakout,
    period: "Oct 2024 - Present",
    link: "https://getbreakout.ai/",
    headTitle: "Breakout",
    title: "Software Engineer",
    points: [
      "Spearheaded an end‑to‑end admin dashboard using modern best practices to drive efficiency and productivity.",
      "Drove innovation for an Agent Chat widget, overseeing design, implementation, and feature development to elevate UX and product capabilities.",
    ],
    skills: [
      "React",
      "TypeScript",
      "Tailwind",
      "Framer Motion",
      "React Router",
      "React Hooks",
      "React Query",
      "React Context",
      "React Redux",
      "React Redux Toolkit",
      "AWS",
      "Cloudfront CDN",
      "Docker",
      "Kubernetes",
      "ArgoCD",
      "GIT",
      "GitHub/GitLab",
      "Technical Documentation",
    ],
  },
];

const data = {
  summary:
    "An enthusiastic and high‑energy professional with ~4 years of experience building modern web applications. I focus on React, TypeScript, Tailwind, micro‑frontends, API integrations and platform engineering to deliver fast, accessible user experiences.",
  social: {
    linkedin: "https://www.linkedin.com/in/pawankumar1201/",
    github: "https://github.com/PawanEpisode/My-Portfolio",
  },
  skills: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Redux",
    "React Router",
    "Tailwind CSS",
    "Material UI",
    "Sass",
    "Vite",
    "Webpack 5",
    "Jest",
    "REST APIs",
    "Node basics",
    "AWS",
    "Docker",
    "Kubernetes",
    "ArgoCD",
    "GIT",
    "GitHub/GitLab",
    "Technical Documentation",
    "Debugging",
    "Testing",
    "Software Design & Code Development",
  ],
  timeline,
  projects: projects,
  certificates: certificates,
  extensiveSkills: extensiveSkills,
  conceptTags: conceptTags,
};

export default data;
